//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.


module Quantium.Recruitment.ApiServices.Models {
	export class AdminDto extends Quantium.Recruitment.ApiServices.Models.Identifiable
	{
		public FirstName: string;
		public LastName: string;
		public Email: string;
		public Mobile: number;
		public IsActive: boolean;
		public DepartmentId: number;
	}
	export class CandidateDto extends Quantium.Recruitment.ApiServices.Models.Identifiable
	{
		public FirstName: string;
		public LastName: string;
		public Email: string;
		public Mobile: number;
		public IsActive: boolean;
		public JobId: number;
		public TestId: number;
	}
	export class CandidateSelectedOptionDto extends Quantium.Recruitment.ApiServices.Models.Identifiable
	{
		public ChallengeId: number;
		public OptionId: number;
	}
	export class ChallengeDto extends Quantium.Recruitment.ApiServices.Models.Identifiable
	{
		public TestId: number;
		public QuestionId: number;
		public StartTime: any;
		public AnsweredTime: any;
		public Question: Quantium.Recruitment.ApiServices.Models.QuestionDto;
		public CandidateSelectedOptions: Quantium.Recruitment.ApiServices.Models.CandidateSelectedOptionDto[];
	}
	export class DepartmentDto extends Quantium.Recruitment.ApiServices.Models.Identifiable
	{
		public Name: string;
		public Jobs: Quantium.Recruitment.ApiServices.Models.JobDto[];
		public Admins: Quantium.Recruitment.ApiServices.Models.AdminDto[];
	}
	export class Identifiable
	{
		public Id: number;
	}
	export class JobDto
	{
		public Title: string;
		public Profile: string;
		public DepartmentId: number;
		public Candidates: Quantium.Recruitment.ApiServices.Models.CandidateDto[];
		public Labels: Quantium.Recruitment.ApiServices.Models.LabelDto[];
	}
	export class LabelDto extends Quantium.Recruitment.ApiServices.Models.Identifiable
	{
		public Name: string;
		public JobId: number;
		public TestId: number;
	}
	export class OptionDto extends Quantium.Recruitment.ApiServices.Models.Identifiable
	{
		public QuestionId: number;
		public Text: string;
		public Image: number[];
		public IsAnswer: boolean;
	}
	export class QuestionDto extends Quantium.Recruitment.ApiServices.Models.Identifiable
	{
		public QuestionGroupId: number;
		public Text: string;
		public Image: number[];
		public TimeInSeconds: number;
		public QuestionGroup: Quantium.Recruitment.ApiServices.Models.QuestionGroupDto;
		public Options: Quantium.Recruitment.ApiServices.Models.OptionDto[];
	}
	export class QuestionGroupDto extends Quantium.Recruitment.ApiServices.Models.Identifiable
	{
		public Description: string;
	}
	export class TestDto extends Quantium.Recruitment.ApiServices.Models.Identifiable
	{
		public Name: string;
		public Labels: Quantium.Recruitment.ApiServices.Models.LabelDto[];
		public Challenges: Quantium.Recruitment.ApiServices.Models.ChallengeDto[];
		public Candidates: Quantium.Recruitment.ApiServices.Models.CandidateDto[];
	}
}
