//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.


module Quantium.Recruitment.ApiServices.Models {
	export class AdminDto
	{
		public Id: number;
		public FirstName: string;
		public LastName: string;
		public Email: string;
		public Mobile: number;
		public IsActive: boolean;
		public DepartmentId: number;
	}
	export class CandidateDto
	{
		public Id: number;
		public FirstName: string;
		public LastName: string;
		public Email: string;
		public Mobile: number;
		public IsActive: boolean;
		public JobId: number;
		public TestId: number;
	}
	export class CandidateSelectedOptionDto
	{
		public Id: number;
		public ChallengeId: number;
		public OptionId: number;
	}
	export class ChallengeDto
	{
		public Id: number;
		public TestId: number;
		public QuestionId: number;
		public StartTime: any;
		public AnsweredTime: any;
		public Question: Quantium.Recruitment.ApiServices.Models.QuestionDto;
		public CandidateSelectedOptions: Quantium.Recruitment.ApiServices.Models.CandidateSelectedOptionDto[];
	}
	export class DepartmentDto
	{
		public Id: number;
		public Name: string;
		public Jobs: Quantium.Recruitment.ApiServices.Models.JobDto[];
		public Admins: Quantium.Recruitment.ApiServices.Models.AdminDto[];
	}
	export class JobDto
	{
		public Id: number;
		public Title: string;
		public Profile: string;
		public DepartmentId: number;
		public Candidates: Quantium.Recruitment.ApiServices.Models.CandidateDto[];
		public Labels: Quantium.Recruitment.ApiServices.Models.LabelDto[];
	}
	export class LabelDto
	{
		public Id: number;
		public Name: string;
		public JobId: number;
		public TestId: number;
	}
	export class OptionDto
	{
		public Id: number;
		public QuestionId: number;
		public Text: string;
		public IsAnswer: boolean;
	}
	export class QuestionDto
	{
		public Id: number;
		public QuestionGroupId: number;
		public Text: string;
		public TimeInSeconds: number;
		public QuestionGroup: Quantium.Recruitment.ApiServices.Models.QuestionGroupDto;
		public Options: Quantium.Recruitment.ApiServices.Models.OptionDto[];
	}
	export class QuestionGroupDto
	{
		public Id: number;
		public Description: string;
	}
	export class TestDto
	{
		public Id: number;
		public Name: string;
		public Labels: Quantium.Recruitment.ApiServices.Models.LabelDto[];
		public Challenges: Quantium.Recruitment.ApiServices.Models.ChallengeDto[];
	}
}
