SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- To Fetch the clients to whom password needs to be sent.
CREATE PROCEDURE GETCLIENTS
AS
BEGIN
SELECT EMAIL,FIRSTNAME FROM CANDIDATE WHERE PASSWORDSENT=0
UNION
SELECT EMAIL,FIRSTNAME FROM ADMIN WHERE PASSWORDSENT=0
END
GO

-- To Update a client when a random password is sent for him.

CREATE PROCEDURE UPDATEUSER(
@EMAIL VARCHAR(100)
)
AS
BEGIN
UPDATE CANDIDATE SET PASSWORDSENT=1 WHERE EMAIL=@EMAIL
UPDATE ADMIN SET   PASSWORDSENT=1 WHERE EMAIL=@EMAIL
END
GO

-- To Fetch clients to whom a mail regarding test generation needs to be sent 

CREATE PROCEDURE GETTESTMAILCLIENTS
AS 
BEGIN
SELECT EMAIL,FIRSTNAME FROM CANDIDATE WHERE TESTMAILSENT=2
END
GO

-- To Update a client when a test genration information was sent to him.

CREATE PROCEDURE UPDATETESTMAILCLIENTS(
@EMAIL VARCHAR(100)
)
AS
BEGIN
UPDATE CANDIDATE SET TESTMAILSENT=3 WHERE EMAIL=@EMAIL
END



